# Site wide configuration

title: Shundake's Blog
locale: en_US
description: Um blog para dicas, tutoriais, brainfarts e outros assuntos relacionados a TI em geral.
logo: site-logo.png
search: true
url: http://blog.shundake.xyz

# Jekyll configuration

permalink:   /:categories/:title.html
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

twitterAccountName: shundake
facebookDevAppId: 541394239351629

# Site owner
owner:
  name: Rodrigo 'Shun' Namba Dake
  avatar: bio-photo.jpg
  email: rodrigodake@gmail.com
  disqus-shortname:
  twitter: shundake
  facebook: shundakesblog
  github: shundake
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: rodrigodake
  instagram: shundake
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: rodrigodake
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
